### ISSUE TITLE
error: recursion limit reached while expanding `$crate::cfg_aliases!`

### ISSUE THREAD

**Issue by Wandalen** [katharostech/cfg_aliases#3]
Does not work for me, even with simple config. Is that suppose to be working?

```rust
  cfg_aliases!
  {
    // etc
    nalgebra_ops_x : { feature = "nalgebra_ops" }
    cgmath_ops :
    {
      not( nalgebra_ops_x )
    },
  }
```

To reproduce the problem you may run the MRE from here [repo](https://github.com/Wandalen/RustPractice/tree/master/all/problem_cfg_aliases).

**Comment by zicklag** [comment]
Hey there!

You just missed a comma after the first rule. Try this:

```rust
  cfg_aliases!
  {
    // etc
    nalgebra_ops_x : { feature = "nalgebra_ops" },
    cgmath_ops :
    {
      not( nalgebra_ops_x )
    },
  }
```
