### ISSUE TITLE
v0.2.1

### ISSUE THREAD

**Issue by dj8yfo** [katharostech/cfg_aliases#9]
@zicklag please return https://github.com/katharostech/cfg_aliases/releases/tag/v0.2.1 to master, it's frightening

**Comment by zicklag** [comment]
@dj8yfo I'm sorry, I don't understand what you're asking me to do. Is there a problem you're having with `v0.2.1`?

**Comment by dj8yfo** [comment]
i'm asking you to push the released tag to `master`, i, frankly speaking, don't see a reason, why it shouldn't be in the `master` branch, it's confusing

**Comment by zicklag** [comment]
Ah, I see. Looks like when I pushed I only pushed the tag, which was unintentional. Fixed. :heavy_check_mark:
